import { useEffect } from 'react';

import type { AppProps } from 'next/app';
import Head from 'next/head';
import Router from 'next/router';

import nProgress from 'nprogress';
import { Provider } from 'react-redux';

import { wrapper } from '@store/index';
import '@styles/globals.scss';

nProgress.configure({ showSpinner: true });

function App({ Component, ...rest }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(rest);

  useEffect(() => {
    Router.events.on('routeChangeStart', () => {
      nProgress.start();
    });

    Router.events.on('routeChangeComplete', () => {
      nProgress.done();
    });

    Router.events.on('routeChangeError', () => {
      nProgress.done();
    });
  }, [Router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <Component {...props.pageProps} />
      </Provider>
    </>
  );
}

export default App;
